### ISSUE TITLE
Custom Cooldowns

### ISSUE THREAD

**Issue by YodaPY** [tandemdude/hikari-lightbulb#57]
### Summary
Allow for dynamic cooldowns that vary based on a given predicate

### Ideal implementation
```py
def predicate(ctx: Context) -> Cooldown:
    if ctx.author_id == 123456789:
        return Cooldown(60, 1, UserBucket)

@custom_cooldown(predicate)
@command()
async def test(ctx: Context) -> None: ...
```

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by norinorin** [comment]
`predicate`? Shouldn't `predicate` return boolean? Anyway, what I could think of is to pass a callback that returns a bucket object instead. That way the `CooldownManager.add_cooldown` method can use its own bucket if there's no callback passed, otherwise, use the bucket returned from the callback. What do you think of that? I might try to make a PR.

**Comment by YodaPY** [comment]
Oops, my bad, just used smth. named `predicate` and somehow it affected my writing. Also, sounds good, go for it.
